/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitusebastian (https://sketchfab.com/nitusebastian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/team-fortress-2-engineer-toolbox-04f7131a03b04fd48b3bcbad21e5c043
Title: Team Fortress 2 Engineer Toolbox
*/

import React, { useRef } from "react";
import { motion } from "framer-motion-3d";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function ToolBox(props) {
  const { nodes, materials } = useGLTF("/team_fortress_2_engineer_toolbox.glb");
  const { viewport } = useThree();
  return (
    <motion.group
      {...props}
      dispose={null}
      initial={{ opacity: 0 }}
      animate={{
        opacity: props.section === 1 ? 1 : 0,
        z: props.section === 1 ? 0 : -10,
        y: props.section === 1 ? -viewport.height - viewport.height / 4 : -1.5,
      }}
    >
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_364_low_Toolbox_0.geometry}
          material={materials.Toolbox}
          color={"hotpink"}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_362_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_361_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_360_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_357_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pipe002_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_339_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_338_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pipe001_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_317_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid_375_low_Toolbox_0.geometry}
          material={materials.Toolbox}
        />
      </group>
    </motion.group>
  );
}

useGLTF.preload("/team_fortress_2_engineer_toolbox.glb");
